services:
  rag-server:
    build: .
    container_name: cheeseade-rag-server
    env_file:
      - ../.env.global
      - .env
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1   
    volumes:
      - ./docs:/app/docs:ro
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - rag-init

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # 의존성 확인 서비스
  rag-init:
    image: curlimages/curl:latest
    container_name: cheeseade-rag-init
    volumes:
      - ./startup.sh:/startup.sh
    depends_on:
      ollama-init:
        condition: service_healthy
      milvus:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/startup.sh"]
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - LLM_SERVER_URL=http://${LLM_SERVER_IP}:${LLM_PORT}
      - API_TIMEOUT=120
    restart: "no"